themebeez/simple-gdpr-cookie-compliance

README.txt, admin/class-simple-gdpr-cookie-compliance-settings.php, admin/css/simple-gdpr-cookie-compliance-admin.css, admin/js/simple-gdpr-cookie-compliance-admin.js, admin/partials/simple-gdpr-cookie-compliance-admin-page.php, includes/class-simple-gdpr-cookie-compliance.php, languages/simple-gdpr-cookie-compliance.pot, public/js/simple-gdpr-cookie-compliance-public.js, simple-gdpr-cookie-compliance.php
** JS issue fixed
* Form notice added
=> 1.0.1 Update

README.txt, simple-gdpr-cookie-compliance.php
=> 1.0.2 Update

README.txt, simple-gdpr-cookie-compliance.php
Tested on WordPress version 5.5
=> = 1.0.3 - August 13, 2020 =

README.txt, admin/class-simple-gdpr-cookie-compliance-admin.php, admin/class-simple-gdpr-cookie-compliance-settings.php, admin/css/simple-gdpr-cookie-compliance-admin.css, admin/js/simple-gdpr-cookie-compliance-admin.js, admin/js/wp-color-picker-alpha.js, includes/class-simple-gdpr-cookie-compliance.php, public/assets/build/js/simple-gdpr-cookie-compliance-public.js, public/class-simple-gdpr-cookie-compliance-public.php, public/partials/simple-gdpr-cookie-compliance-public-display.php, simple-gdpr-cookie-compliance.php
* Added: Options customization options.
* Fix: Other minor issues
=> 1.0.4 Update

admin/css/simple-gdpr-cookie-compliance-admin.css, public/class-simple-gdpr-cookie-compliance-public.php
=> Popup design issue fixed

public/class-simple-gdpr-cookie-compliance-public.php
Fix Full width conditional style
=> Fix Full width conditional style

README.txt, includes/class-simple-gdpr-cookie-compliance.php, simple-gdpr-cookie-compliance.php
=> 🐛 = 1.0.5 - Feb 19, 2021 =

includes/class-simple-gdpr-cookie-compliance.php, simple-gdpr-cookie-compliance.php
=> Setting option bug fixed

README.txt, simple-gdpr-cookie-compliance.php
=> == 1.0.6, 20 July 2021 ==

README.txt, languages/simple-gdpr-cookie-compliance.pot, public/class-simple-gdpr-cookie-compliance-public.php, simple-gdpr-cookie-compliance.php
=> 1.0.7 Update

simple-gdpr-cookie-compliance.php
=> Version change

admin/class-simple-gdpr-cookie-compliance-admin.php, languages/simple-gdpr-cookie-compliance.pot
=> Enqueue Update

README.txt, simple-gdpr-cookie-compliance.php
- Tested: WordPress version 5.9
- Tested: PHP version 7.4
=> ✅ = 1.0.8 Tested with WP 5.9 =

README.txt, includes/class-simple-gdpr-cookie-compliance.php, public/assets/build/js/simple-gdpr-cookie-compliance-public.js, public/class-simple-gdpr-cookie-compliance-public.php, simple-gdpr-cookie-compliance.php
- Fixed: Session Cookie issue fixed.
- Added: Multisite support.
=> Session Cookie Issue Fixed & Added Multisite Support

README.txt
Added: addonify as contributor.
=> Added: addonify as contributor.

.gitignore, gulpfile.js, package-lock.json, package.json
Added: gulp file & package.json
=> Added: gulp file & package.json

README.txt, simple-gdpr-cookie-compliance.php
- Tested: with WordPress version 6.0.2.
=> Tested: with WordPress version 6.0.2.

README.txt, includes/udp/class-udp-agent.php, includes/udp/init.php, languages/simple-gdpr-cookie-compliance.pot, simple-gdpr-cookie-compliance.php
=> Updated: POT & version.

README.txt, admin/class-simple-gdpr-cookie-compliance-admin.php, admin/class-simple-gdpr-cookie-compliance-settings.php, includes/class-simple-gdpr-cookie-compliance-activator.php, includes/class-simple-gdpr-cookie-compliance-deactivator.php, includes/class-simple-gdpr-cookie-compliance-i18n.php, includes/class-simple-gdpr-cookie-compliance-loader.php, includes/class-simple-gdpr-cookie-compliance.php, includes/udp/class-udp-agent.php, includes/udp/init.php, public/class-simple-gdpr-cookie-compliance-public.php, public/partials/simple-gdpr-cookie-compliance-public-display.php, simple-gdpr-cookie-compliance.php
- Update: Static texts in UDP Agents are now translation ready.
- Update: WPCS implemented.
- Fix: Minor PHP error.
=> WPCS implementation, UDP update, PHP error fix

README.txt
=> Updated: release date.
